apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-feet-api

spec:
  replicas: 5
  selector:
    matchLabels:
      app: fast-feet-api
  template:
    metadata:
      labels:
        app: fast-feet-api
    spec:
      containers:
        - name: fast-feet-api
          image: vinciusaf/fast-feet-api:97c5bcb
          ports:
           - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi