apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-feet-api
  namespace: k8s-lab-ns

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20% 
  selector:
    matchLabels:
      app: fast-feet-api
  template:
    metadata:
      labels:
        app: fast-feet-api
    spec:
      containers:
        - name: fast-feet-api
          image: vinciusaf/fast-feet-api:f09532a
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fast-feet-api-config
            - secretRef:
                name: fast-feet-api-secrets
          ports:
           - containerPort: 80
          resources:
            requests:
              cpu: 150m
              memory: 160Mi
            limits:
              cpu: 300m
              memory: 320Mi