apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: fast-feet-api-hpa
  namespace: k8s-lab-ns
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: fast-feet-api
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 75

# HPA V1 is deprecated