apiVersion: v1
kind: Pod

metadata:
  name: fast-feet-api

spec:
  containers:
    - name: fast-feet-api
      image: fast-feet-api:trixie-perl
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
