apiVersion: v1
kind: PersistentVolume

metadata:
  name: k8s-lab-pv
  namespace: k8s-lab-ns
  labels:
    name: k8s-lab-pv

spec: 
  capacity:
    storage: 5Gi
  accessModes: 
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data