apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: k8s-lab-pvc
  namespace: k8s-lab-ns

spec: 
  resources:
    requests:
        storage: 1Gi
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  selector:
    matchLabels: 
      name: k8s-lab-pv
