apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: k8s-lab-storage-class
  namespace: k8s-lab-ns

provisioner: kubernetes.io/no-provisioner
reclaimPolicy:  Retain
volumeBindingMode: WaitForFirstConsumer